### ISSUE TITLE
Checkbox tree not rendering

### ISSUE THREAD

**Issue by abidhkm** [hoaphantn7604/react-native-checkbox-tree#4]
RN version : 0.67.2
The issue happens in Android. Nor checked IOS yet.
The tree is not rendered, only something like a small symbol coming up as shown below in the pic.
The code I used is exactly same as given in the example here https://github.com/hoaphantn7604/react-native-checkbox-tree
 
![image](https://user-images.githubusercontent.com/22368311/160252644-98af8ed1-c985-424b-a440-c9fa458ea87a.png)

**Comment by abidhkm** [comment]
just closing this, for now, will create a new issue with details after going through the code.
It would be great if we can improve the documentation

**Comment by ntd10102000** [comment]
Can you give me the source code you have successfully run? i had the same problem, thanks

**Comment by ntd10102000** [comment]
@abidhkm  Can you give me the source code you have successfully run? i had the same problem, thanks

**Comment by hoaphantn7604** [comment]
Hi,
Sorry I updated this package but not updated the documentation yet.
I will update the document.
